# Generated by Django 5.1.2 on 2024-10-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='available_day',
            field=models.CharField(max_length=20),
        ),
    ]
